kind = "web"
previewPath = "/"
title = "Jastip Anggun Jaya"
version = "1.0.0"
id = "artifacts/jastip-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18281

[services.development]
run = "pnpm --filter @workspace/jastip-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jastip-app", "run", "build" ]
publicDir = "artifacts/jastip-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18281"
BASE_PATH = "/"
